/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Color;
import java.text.DecimalFormat;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Daylton
 * Escreva um programa que permita a compra de um modelo de telefone celular. 
 * O cliente deve escolher o modelo em uma caixa de combinação, especificar a operadora por meio de
 * caixa de seleção e o tipo de pagamento (à vista, 3 vezes ou 6 vezes) utilizando botões de rádio.
 * Além disso, é possível escolher entre os seguintes acessórios: bateria adicional, 
 * capa ou fone de ouvido. Você deve considerar os preços dos modelos celulares e demais acessórios
 * para efetuar o cálculo do valor total. As compras à vista oferecem 5% de desconto.
 * Para as compras a prazo, o valor das parcelas deve ser exibido também. 
 * Desafio: Inclua uma validação para que o usuário escolha aparelhos para no máximo duas operadoras (dual chip)
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
        
    int modelo, operadora1, operadora2, aux, parceleInt;
    float valorAparelho, desconto, acessorios, parcela, total;
    ImageIcon aparelho;
    Image nexus, htc,iphone6, iphone6plus,lumia,motoMaxx, motoG, motoX, galaxyNote, galaxyS5;
    public Main() {
        initComponents();
        Image Icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/icon.png") );
        this.setIconImage(Icon);
        this.setTitle("Buy do not Complain");        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngPagemento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbModelo = new javax.swing.JComboBox();
        btnComprar = new javax.swing.JButton();
        lbValor = new javax.swing.JLabel();
        lbOperadora1 = new javax.swing.JLabel();
        cbOperadora2 = new javax.swing.JComboBox();
        cbOperadora1 = new javax.swing.JComboBox();
        lbDualChip = new javax.swing.JLabel();
        lbPagamento = new javax.swing.JLabel();
        rbVista = new javax.swing.JRadioButton();
        rb3vezes = new javax.swing.JRadioButton();
        rb6vezes = new javax.swing.JRadioButton();
        lbAcessorios = new javax.swing.JLabel();
        cbxBateria = new javax.swing.JCheckBox();
        cbxFone = new javax.swing.JCheckBox();
        cbxCapa = new javax.swing.JCheckBox();
        Valor = new javax.swing.JLabel();
        lbMensagem = new javax.swing.JLabel();
        pnValor = new javax.swing.JPanel();
        lbVezes = new javax.swing.JLabel();
        lbParcelas = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnProdutos = new javax.swing.JPanel();
        lbProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("pixel dead", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buy Your Smartphone");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha o modelo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("pixel dead", 0, 24))); // NOI18N

        cbModelo.setFont(new java.awt.Font("pixel dead", 3, 18)); // NOI18N
        cbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----------------------------------", " - Google Nexus 6", " - HTC One M8", " - iPhone 6 ", " - iPhone 6 Plus", " - Microsoft Lumia 930", " - Motorola Maxx", " - Motorola Moto G", " - Motorola Moto X", " - Samsung Galaxy Note 4", " - Samsung Galaxy S5", " ", " ", " ", " ", " " }));
        cbModelo.setToolTipText("");
        cbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeloActionPerformed(evt);
            }
        });

        btnComprar.setFont(new java.awt.Font("pixel dead", 0, 24)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.setEnabled(false);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        lbValor.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        lbValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValor.setText("Valor");
        lbValor.setEnabled(false);

        lbOperadora1.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        lbOperadora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOperadora1.setText("Operadora");
        lbOperadora1.setEnabled(false);

        cbOperadora2.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        cbOperadora2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ---------------", " - Bay ", " - Dark", " - Dead", " - Unsigned" }));
        cbOperadora2.setEnabled(false);
        cbOperadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOperadora2ActionPerformed(evt);
            }
        });

        cbOperadora1.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        cbOperadora1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ---------------", " - Bay ", " - Dark", " - Dead", " - Unsigned" }));
        cbOperadora1.setEnabled(false);
        cbOperadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOperadora1ActionPerformed(evt);
            }
        });

        lbDualChip.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        lbDualChip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbPagamento.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        lbPagamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPagamento.setText("Pagamento");
        lbPagamento.setEnabled(false);

        btngPagemento.add(rbVista);
        rbVista.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        rbVista.setText("A Vista");
        rbVista.setEnabled(false);
        rbVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVistaActionPerformed(evt);
            }
        });

        btngPagemento.add(rb3vezes);
        rb3vezes.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        rb3vezes.setText("3x vezes");
        rb3vezes.setEnabled(false);
        rb3vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3vezesActionPerformed(evt);
            }
        });

        btngPagemento.add(rb6vezes);
        rb6vezes.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        rb6vezes.setText("6x vezes");
        rb6vezes.setEnabled(false);
        rb6vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6vezesActionPerformed(evt);
            }
        });

        lbAcessorios.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        lbAcessorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAcessorios.setText("Acessorios");
        lbAcessorios.setEnabled(false);

        cbxBateria.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        cbxBateria.setText("Bateria Adicional");
        cbxBateria.setEnabled(false);
        cbxBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBateriaActionPerformed(evt);
            }
        });

        cbxFone.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        cbxFone.setText("Fone de Ouvido");
        cbxFone.setEnabled(false);
        cbxFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFoneActionPerformed(evt);
            }
        });

        cbxCapa.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        cbxCapa.setText("Capa");
        cbxCapa.setEnabled(false);
        cbxCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCapaActionPerformed(evt);
            }
        });

        Valor.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        Valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbMensagem.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbOperadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbOperadora1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(Valor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbDualChip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbOperadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lbMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxFone)
                                .addComponent(cbxBateria)
                                .addComponent(cbxCapa))
                            .addGap(114, 114, 114))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbVista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb3vezes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rb6vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnComprar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPagamento)
                    .addComponent(rbVista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb3vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb6vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(cbxBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbOperadora1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOperadora1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbOperadora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDualChip, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbAcessorios)
                            .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
        );

        pnValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor da Conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("pixel dead", 0, 24))); // NOI18N
        pnValor.setEnabled(false);

        lbVezes.setFont(new java.awt.Font("pixel dead", 0, 36)); // NOI18N
        lbVezes.setForeground(new java.awt.Color(0, 204, 0));
        lbVezes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbParcelas.setFont(new java.awt.Font("pixel dead", 0, 36)); // NOI18N
        lbParcelas.setForeground(new java.awt.Color(0, 204, 0));

        lbValorTotal.setFont(new java.awt.Font("pixel dead", 0, 36)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(0, 204, 0));
        lbValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setFont(new java.awt.Font("pixel dead", 0, 36)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnValorLayout = new javax.swing.GroupLayout(pnValor);
        pnValor.setLayout(pnValorLayout);
        pnValorLayout.setHorizontalGroup(
            pnValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnValorLayout.createSequentialGroup()
                        .addComponent(lbVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnValorLayout.setVerticalGroup(
            pnValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbVezes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lbParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("pixel dead", 0, 18))); // NOI18N
        pnProdutos.setEnabled(false);

        javax.swing.GroupLayout pnProdutosLayout = new javax.swing.GroupLayout(pnProdutos);
        pnProdutos.setLayout(pnProdutosLayout);
        pnProdutosLayout.setHorizontalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnProdutosLayout.setVerticalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutosLayout.createSequentialGroup()
                .addComponent(lbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeloActionPerformed
       modelo  = cbModelo.getSelectedIndex();
      
       switch (modelo)
       {           
           case 1:
           {
               valorAparelho = (float) 1770.0;
               lbValor.setEnabled(cbModelo.isEnabled() );               
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);               
               aparelho = new ImageIcon("nexus6.jpg"); 
               nexus = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 2:
           {
               valorAparelho = (float) 1750.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/htc.jpg") );
               htc = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 3:
           {
               valorAparelho = (float) 3200.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/iphone6.jpg") );
               iphone6 = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 4:
           {
               valorAparelho = (float) 3800.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/iphone6plus.jpg") );
               iphone6plus = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 5:
           {
               valorAparelho = (float) 1800.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/lumia.jpg") );
               lumia = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 6:
           {
               valorAparelho = (float) 2200.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/motoMaxx.jpg") );
               motoMaxx = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 7:
           {
               valorAparelho = (float) 799.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               lbDualChip.setText("2 Operadora");
               cbOperadora2.setEnabled(cbModelo.isEnabled() );
               aparelho = new ImageIcon(Main.class.getResource("../imagens/motoG.jpg") );
               motoG = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);  
               aux = 2;
               break;
           }
           case 8:
           {
               valorAparelho = (float) 1499.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/motoX.jpg") );
               motoX = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 9:
           {
               valorAparelho = (float) 2800.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/galaxyNote.jpg") );
               galaxyNote = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           case 10:
           {
               valorAparelho = (float) 2300.0;
               lbValor.setEnabled(cbModelo.isEnabled() );
               Valor.setText("R$ " + valorAparelho);
               lbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora1.setEnabled(cbModelo.isEnabled() );
               cbOperadora2.setEnabled(false);
               aparelho = new ImageIcon(Main.class.getResource("../imagens/galaxyS5.jpg") );
               galaxyS5 = aparelho.getImage().getScaledInstance(lbProduto.getWidth(),lbProduto.getHeight(), Image.SCALE_DEFAULT);  
               lbMensagem.setText(null);
               aux = 1;
               break;
           }
           default:
           {
               lbMensagem.setText("Informe um modelo!");
               lbMensagem.setForeground(Color.red);
           }
       }
    }//GEN-LAST:event_cbModeloActionPerformed

    private void cbOperadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOperadora1ActionPerformed
        operadora1 = cbOperadora1.getSelectedIndex();
        if (operadora1 == 0)
        {
            lbMensagem.setText("Informe uma operadora!");
            lbMensagem.setForeground(Color.red);
        }
        else
        {
            if (aux == 1)
            {
                lbMensagem.setText(null);
                lbPagamento.setEnabled(cbOperadora1.isEnabled() );
                rbVista.setEnabled(cbOperadora1.isEnabled() );
                rb3vezes.setEnabled(cbOperadora1.isEnabled() );
                rb6vezes.setEnabled(cbOperadora1.isEnabled() );  
            }
            else
            {
                lbMensagem.setText(null);
            }
        }
        
    }//GEN-LAST:event_cbOperadora1ActionPerformed

    private void cbOperadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOperadora2ActionPerformed
        operadora2 = cbOperadora2.getSelectedIndex();
        if (operadora2 == 0)
        {
            lbMensagem.setText("Informe uma operadora!");
            lbMensagem.setForeground(Color.red);
        }
        else
        {
            lbMensagem.setText(null);
            lbPagamento.setEnabled(cbOperadora2.isEnabled() );
            rbVista.setEnabled(cbOperadora2.isEnabled() );
            rb3vezes.setEnabled(cbOperadora2.isEnabled() );
            rb6vezes.setEnabled(cbOperadora2.isEnabled() );           
        }
        
    }//GEN-LAST:event_cbOperadora2ActionPerformed

    private void rbVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVistaActionPerformed
        aux = 1;
        lbAcessorios.setEnabled(rbVista.isSelected() );
        cbxBateria.setEnabled(rbVista.isSelected() );
        cbxFone.setEnabled(rbVista.isSelected() );
        cbxCapa.setEnabled(rbVista.isSelected() );        
    }//GEN-LAST:event_rbVistaActionPerformed

    private void rb3vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3vezesActionPerformed
        aux = 3;
        lbAcessorios.setEnabled(rb3vezes.isSelected() );
        cbxBateria.setEnabled(rb3vezes.isSelected() );
        cbxFone.setEnabled(rb3vezes.isSelected() );
        cbxCapa.setEnabled(rb3vezes.isSelected() );
    }//GEN-LAST:event_rb3vezesActionPerformed

    private void rb6vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6vezesActionPerformed
        aux = 6;  
        lbAcessorios.setEnabled(rb6vezes.isSelected() );
        cbxBateria.setEnabled(rb6vezes.isSelected() );
        cbxFone.setEnabled(rb6vezes.isSelected() );
        cbxCapa.setEnabled(rb6vezes.isSelected() );
    }//GEN-LAST:event_rb6vezesActionPerformed

    private void cbxBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBateriaActionPerformed
        acessorios += 50;
        btnComprar.setEnabled(cbxBateria.isSelected() );
    }//GEN-LAST:event_cbxBateriaActionPerformed

    private void cbxFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFoneActionPerformed
        acessorios += 40;
        btnComprar.setEnabled(cbxFone.isSelected() );
    }//GEN-LAST:event_cbxFoneActionPerformed

    private void cbxCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCapaActionPerformed
        acessorios += 25;
        btnComprar.setEnabled(cbxCapa.isSelected() );
    }//GEN-LAST:event_cbxCapaActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        switch (aux)
        {
            case 1:
            {
                desconto = (float) ((valorAparelho + acessorios) * 0.05);
                total = (valorAparelho + acessorios) - desconto;
                parcela = total;
                pnValor.setEnabled(btnComprar.isEnabled() );
                pnProdutos.setEnabled(btnComprar.isEnabled() );
                                
                DecimalFormat df1 = new DecimalFormat("0.00");
                lbVezes.setText("1x ");
                lbParcelas.setText("R$" + df1.format(parcela) );
                lbValorTotal.setText("Total = R$" + df1.format(total) );
                
                 switch (modelo)
                 {
                     case 1:
                     {
                        lbProduto.setIcon(new ImageIcon(nexus) );
                     }
                     case 2:
                     {
                        lbProduto.setIcon(new ImageIcon(htc) );
                     }
                     case 3:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6) );
                     }
                     case 4:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6plus) );
                     }
                     case 5:
                     {
                         lbProduto.setIcon(new ImageIcon(lumia) );
                     }
                     case 6:
                     {
                         lbProduto.setIcon(new ImageIcon(motoMaxx) );
                     }
                     case 7:
                     {
                         lbProduto.setIcon(new ImageIcon(motoG) );
                     }
                     case 8:
                     {
                         lbProduto.setIcon(new ImageIcon(motoX) );
                     }
                     case 9:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyNote) );
                     }
                     case 10:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyS5) );
                     } 
                     default:
                     {
                         lbMensagem.setText("ERROR!!!");
                         lbMensagem.setForeground(Color.red);
                     }
                 }                            
            }
            
            case 3:
            {
                total = valorAparelho + acessorios;
                parcela = total / 3;
                pnValor.setEnabled(btnComprar.isEnabled() );
                pnProdutos.setEnabled(btnComprar.isEnabled() );
                                
                DecimalFormat df2 = new DecimalFormat("0.00");
                lbVezes.setText("3x ");
                lbParcelas.setText("R$" + df2.format(parcela) );
                lbValorTotal.setText("Total = R$" + df2.format(total) );
                
                switch (modelo)
                 {
                     case 1:
                     {
                        lbProduto.setIcon(new ImageIcon(nexus) );
                     }
                     case 2:
                     {
                        lbProduto.setIcon(new ImageIcon(htc) );
                     }
                     case 3:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6) );
                     }
                     case 4:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6plus) );
                     }
                     case 5:
                     {
                         lbProduto.setIcon(new ImageIcon(lumia) );
                     }
                     case 6:
                     {
                         lbProduto.setIcon(new ImageIcon(motoMaxx) );
                     }
                     case 7:
                     {
                         lbProduto.setIcon(new ImageIcon(motoG) );
                     }
                     case 8:
                     {
                         lbProduto.setIcon(new ImageIcon(motoX) );
                     }
                     case 9:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyNote) );
                     }
                     case 10:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyS5) );
                     } 
                     default:
                     {
                         lbMensagem.setText("ERROR!!!");
                         lbMensagem.setForeground(Color.red);
                     }
                 } 
            }
            
            case 6:
            {
                total = valorAparelho + acessorios;
                parcela = total / 6; 
                pnValor.setEnabled(btnComprar.isEnabled() );
                pnProdutos.setEnabled(btnComprar.isEnabled() );
                                
                DecimalFormat df3 = new DecimalFormat("0.00");
                lbVezes.setText("6x ");
                lbParcelas.setText("R$" + df3.format(parcela) );
                lbValorTotal.setText("Total = R$" + df3.format(total) );
                
                switch (modelo)
                 {
                     case 1:
                     {
                        lbProduto.setIcon(new ImageIcon(nexus) );
                     }
                     case 2:
                     {
                        lbProduto.setIcon(new ImageIcon(htc) );
                     }
                     case 3:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6) );
                     }
                     case 4:
                     {
                         lbProduto.setIcon(new ImageIcon(iphone6plus) );
                     }
                     case 5:
                     {
                         lbProduto.setIcon(new ImageIcon(lumia) );
                     }
                     case 6:
                     {
                         lbProduto.setIcon(new ImageIcon(motoMaxx) );
                     }
                     case 7:
                     {
                         lbProduto.setIcon(new ImageIcon(motoG) );
                     }
                     case 8:
                     {
                         lbProduto.setIcon(new ImageIcon(motoX) );
                     }
                     case 9:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyNote) );
                     }
                     case 10:
                     {
                         lbProduto.setIcon(new ImageIcon(galaxyS5) );
                     } 
                     default:
                     {
                         lbMensagem.setText("ERROR!!!");
                         lbMensagem.setForeground(Color.red);
                     }
                 }
            }
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Valor;
    private javax.swing.JButton btnComprar;
    private javax.swing.ButtonGroup btngPagemento;
    private javax.swing.JComboBox cbModelo;
    private javax.swing.JComboBox cbOperadora1;
    private javax.swing.JComboBox cbOperadora2;
    private javax.swing.JCheckBox cbxBateria;
    private javax.swing.JCheckBox cbxCapa;
    private javax.swing.JCheckBox cbxFone;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAcessorios;
    private javax.swing.JLabel lbDualChip;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JLabel lbOperadora1;
    private javax.swing.JLabel lbPagamento;
    private javax.swing.JLabel lbParcelas;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JLabel lbVezes;
    private javax.swing.JPanel pnProdutos;
    private javax.swing.JPanel pnValor;
    private javax.swing.JRadioButton rb3vezes;
    private javax.swing.JRadioButton rb6vezes;
    private javax.swing.JRadioButton rbVista;
    // End of variables declaration//GEN-END:variables
}
